version: '3.7'

services:
  posgres_db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always

  mongo_dev:
    image : mongo:latest
    container_name: mongodb
    env_file:
      - .env
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: always
  
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    # Run a command against the development stage of the image
    command: > 
          sh -c "
                npm run migration:generate -- database/migrations/NewMigration &&
                npm run migration:run &&
                npm run start:dev 
                "
    ports:
      - 3000:3000
    
    depends_on:
      - mongo_dev
      - posgres_db

networks:
  app-tier:
    driver: bridge